### ISSUE TITLE
Range doesn't work correctly

### ISSUE THREAD

**Issue by Sav22999** [dag7dev/common-voice-tool#3]
Non funziona il RANGE.
Il conteggio dei caratteri superiori funziona bene e restituisce anche correttamente la stringa "Caratteri superiori a quelli consentiti", ma se è troppo corta non restituisce la stringa corretta: restituisce, infatti, la stessa stringa del superamento della soglia max :) correggere

**Comment by Sav22999** [comment]
**update**
Anche il range max non funziona correttamente. C'è una stringa lunghissima che ha proprio saltato...

**Comment by dag7dev** [comment]
Aggiornato alla v0.3! Fammi sapere!

**Comment by Sav22999** [comment]
Ora funziona bene.
(Ancora un errore di stringa -> "troppo lunga" invece di "troppo corta" :P)
