### ISSUE TITLE
Esito su test "approfondito"

### ISSUE THREAD

**Issue by Sav22999** [dag7dev/common-voice-tool#7]
Ho effettuato parecchi test e ho trovato alcune cose da migliorare. Ma, in generale, il programma riesce a gestire quasi tutto :) 
|| Esito OK significa che è stato gestito correttamente || Esito NO significa che non è stato gestito ||
VERSIONE TOOL: UNKNOWN BETA
- Scelta lingua:
   - Inserito un valore differente da quello indicato: **Esito OK** -> Restituisce messaggio "File not found! Exiting..." -> Io mostrerei un messaggio di tipo "Language file not found! Exiting..." specificando che è il file di lingua a non essere stato trovato :)
- range (o chkLen):
   - Inserito valore stringa alfanumerico: **Esito OK**
   - Inserito valore decimale: **Esito NO** -> causa errore successivo nel controllo poiché si aspetta un valore numerico intero (Errore restituito nel controllo successivo "Attesa espressione intera")
- Scelta file:
   - Inserito file insesistente: **Esito OK**
- trim: **Esito NO** -> NON toglie gli spazi a fine riga e, inoltre, toglie tutti i primi spazio.
Esempio:
(Originale)
>"Prova esempio frase numero uno ciao ciao ciao ciao&nbsp;&nbsp;"
(Risultato)
>"Provaesempio frase numero uno ciao ciao ciao&nbsp;nbsp;"
- ac: **Esito OK** -> Suggerimento: Quando viene mostrato "Aggiungo..." aggiungere anche un [OK] se viene aggiunto correttamente, ottenendo, in questo modo: "Aggiungo... [OK]"
- no-empy: **Esito NO** -> STESSO PROBLEMA DI TRIM -> NON CANCELLA LE RIGHE VUOTE E RIMUOVE I PRIMI SPAZI
  - Suggerimento: RINOMINARE LA FUNZIONE IN "noEmpty" -> bisogna seguire una regola di stile. O adotti a tutti il "-" oppure metti le maiuscole. Fare un minestrone confonde parecchio.
- capitalize: **Esito OK**
   - Ho provato anche a mettere differenti caratteri per verificare che trasformasse in maiuscolo ogni cosa e funziona correttamente. Anche le lettere accentate funzionano bene.
- chkPoint: **Esito OK**

Inoltre aggiungere il numero di versione, e non solo il tipo :)

**Comment by dag7dev** [comment]
Grazie Saverio! Ho pushato i cambiamenti nella beta, fammi sapere!

**Comment by Sav22999** [comment]
@dag7dev ho provato a fare lo stesso test oggi.
Stesso esito.
Trim ect. continuano a non funzionare
